/* ********************************************
 *
 * HTTP API Integration Tests
 * Generated by Edda
 * <%=new Date()%>
 *
 * Source restlang files:
 * <% _.each(files,function(file) { %> 
 *  <%= file %>
 * <% }); %>
 *
 * ********************************************/

var assert = require('assert');
var should = require('should');
var ragnarok = require('ragnarok');
var tools = ragnarok.tools;
var client = ragnarok.client;


<% if(!url) throw ('Missing url') %>
var url = '<%=url%>';

var credentials = {};

var init = function(connection){

	<% _.each(api,function(resource) { %> 

		describe('<%=resource.name%>, <%=resource.description%>',function(){

			<% _.each(resource.resource,function(route,key) { %> 

				<-%=JSON.stringify(resource)%>
				
				it('<%=route.description%>',function(done){
					var request = connection['<%=resource.verb%>'];
					request&&request('<%=edda.mock(resource.name,route)%>',function(err,data){
						tools.testOData(data);
						done();
					});
				});

			<% }); %>

		});
		 
	<% }); %>

};

client(url,credentials,function(err,connection) {
	if(err) {
		console.log(err);
	} else {
		init(session);
	}
});